trigger:
- master

variables:
  DisplayVersion: $[counter(variables['DisplayPrefix'], 1)]

stages:
- stage: build
  displayName: 'build'
  jobs:
  - job: build
    timeoutInMinutes: 120
    displayName: 'windows-msvc'
    pool:
      vmImage: windows-2019
    steps:
    - template: ./templates/sync-source.yml
      parameters:
        artifactSource: $(parameters.artifactSource)
        needSubmodules: 'true'
    - template: ./templates/build-msvc.yml
      parameters:
        artifactSource: 'false'
        cache: $(parameters.cache)
        version: $(DisplayVersion)
- stage: release
  displayName: 'release'
  dependsOn: build
  jobs:
    - job: release
      displayName: 'source'
      steps:
        - template: ./templates/release-private-tag.yml
